### ISSUE TITLE
no code

### ISSUE THREAD

**Issue by Chris-Perkins** [njha7/FlamingoV2#1]
**Expected Behavior**  
- there should be code

**Current Behavior**  
- there's no code

**Possible Solution**  
- add code 

**Steps to Reproduce**  
1. view repo
1. there's no code

**Context (Environment)**  
- Prod

Detailed Description  
- I don't want to write one

Possible Implementation
- javascript or swift idk

**Comment by njha7** [comment]
Sorry, initial commit was delayed. I wanted the initial commit to be something that could successfully deploy via AWS CodePipeLines.

**Comment by tdorn** [comment]
#2
