### ISSUE TITLE
Command Parsing Pattern not Scalable

### ISSUE THREAD

**Issue by Chris-Perkins** [njha7/FlamingoV2#18]
https://github.com/njha7/FlamingoV2/blob/cddd6036854ca1f02916ec61612ecf7815584c2c/flamingo.go#L107-L166

The lines of code in the linked snippet will not scale well if additional commands are added. If another feature were to be added, the linked function would easily span 100+ lines. I would suggest the following design strategy: 

### Strategy 1   
* Have each Command Service (Currently Strike, Pasta Service) inherit from an interface `CommandService`.  
  * `CommandService` should implement the following methods: 
    * `canHandleRequest(request []string)` - Used to determine if a Command Service can run the command. For example, the pasta service CAN run `["pasta", "get", "top_prestige"]` but it cannot run `["strike", "tdorno"]`.
    * `executeRequest(request []string)` - Used to execute the request. For example, `["pasta", "list"]` will execute the pasta list command on the Pasta Service.

The strategy for running:
1. Keep a list of Command Services that are running in a list `[]CommandService`
1. For every input command, split it into a list of strings by splitting on new line characters and spaces. In this example, let's call the resulting `[]string` `requestParameters`
1. For each command service in the list described in (1), check `commandService.canHandleRequest(requestParameters)`
  1. If the above check is successful, run `commandService.executeRequest(requestParameters)`

This methodology allows for multiple services to be able to execute on one command while keeping holding up SOLID design principles. Single Responsibility OP.

### Alternative Strategy  
* Keep a map from String -> Void Lambda Function in memory
  * This Lambda function should map to the appropriate Command Service function.

#### Why this isn't the main strategy  
Lambda functions would be annoying to deal with in golang if they do not conform to a common interface. For example, some commands might need string parameters, while others might not. However, if you believe the Command Services this system provides in the future will always be of type `name(args []string)`, this strategy is fast in execution due to map `get` calls being O(1) asymptotically.

I might still suggest putting such behavior in a separate class (`CommandHandler`?) to uphold SOLID principles.

Keep up the scalable work!

**Comment by njha7** [comment]
I'm going to take a hybrid approach between what is currently done and your first suggestion. Services will be responsible for identifying potential invocations and will drop into the service-specific switch in a handle function. All services will implement an interface to maintain that guarantee.

**Comment by njha7** [comment]
e.g. ```PastaService.IsCommand("pasta get xD")``` returns ```true```. ```PastaService.Handle(message)``` is invoked. In ```Handle()``` :

```switch subCommand {
    case "get":
    // do the thing ...
```

**Comment by njha7** [comment]
https://github.com/njha7/FlamingoV2/blob/a40e2c2824cd269faa277cab28b68897cff742d2/flamingo.go#L99-L107

https://github.com/njha7/FlamingoV2/blob/a40e2c2824cd269faa277cab28b68897cff742d2/flamingoservice/pasta.go#L55-L110

**Comment by njha7** [comment]
Fixed in [7f1b7b1](https://github.com/njha7/FlamingoV2/commit/7f1b7b164c841c7cd711f99998f9457f6cfd4dc2)
