### ISSUE TITLE
Use packages to better organize components

### ISSUE THREAD

**Issue by tdorn** [njha7/FlamingoV2#20]
Right now, all the code is housed in the main package. While this is mainly due to Go's shitty workspace limitation, I think we can improve upon this while reducing overall clutter. I suggest that you create contextual subfolders  (services, commands, resources, etc.), as independent packages, to promote a better separation of concerns. This repository will not scale to 200+ developers if everything lives in the main package.

**Comment by njha7** [comment]
Fixed in [09c8751](https://github.com/njha7/FlamingoV2/commit/09c8751e2b45defbc3b2c00df54a40d9ef09bf80). Thanks for insisting on the highest standards!
