### ISSUE TITLE
Large Docker image

### ISSUE THREAD

**Issue by danlemmond** [njha7/FlamingoV2#8]
You could utilize multi-stage builds to avoid using the Go Docker image as it's fairly large. You should be able to compile the Go binary on the Golang image and then copy it to an Alpine image for a smaller footprint.

**Comment by dlemmond** [comment]
Relevant documentation: [here](https://docs.docker.com/develop/develop-images/multistage-build/)

**Comment by danlemmond** [comment]
This is also fixed by #26, we running on Alpine now
